In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

df = pd.read_csv(Path.cwd().parent / "data" / "spy_eod_202303.txt")
df.columns = [k.strip(' ') for k in df.columns]
df

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.01,-0.00069,0.00008,-0.00004,-0.00482,0.00000,1.486360,0.000000,74.8,0.189
1,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.02,-0.00080,0.00011,0.00034,-0.00529,0.00000,1.282980,0.000000,64.8,0.164
2,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.00,-0.00075,0.00014,0.00100,-0.00509,-0.00046,1.162910,,58.8,0.149
3,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.00,-0.00128,0.00020,0.00096,-0.00470,0.00000,1.143500,,57.8,0.146
4,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.00,-0.00050,0.00015,0.00027,-0.00523,-0.00017,1.123140,,56.8,0.144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91230,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.08235,0.00152,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,220.6,0.539
91231,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.08401,0.00146,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,225.6,0.551
91232,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.06465,0.00132,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,230.6,0.563
91233,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.07999,0.00138,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,235.6,0.576
91234,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.05785,0.00116,...,240.32,-1.00000,0.00000,0.00000,0.00000,0.00000,,0.000000,240.6,0.588

In [3]:
quotes = df["[QUOTE_READTIME]"].unique()
strikes = df["[STRIKE]"].unique()
expiries = df["[EXPIRE_DATE]"].unique()

print('num of quotes:', len(quotes))
print('num strikes:', len(strikes))
print('num expiries:', len(expiries))

groups = df.groupby(["[QUOTE_READTIME]"])

for quote_time, group in groups:
    print(len(group["[STRIKE]"].unique()))
    print(len(group["[EXPIRE_DATE]"].unique()))
    print()

num of quotes: 23
num strikes: 289
num expiries: 53
289
32

289
34

289
33

289
33

289
33

289
33

289
34

289
33

289
33

289
33

289
33

289
33

289
32

289
32

289
32

289
32

289
32

289
31

288
31

288
31

288
31

288
32

288
31

In [4]:
df = pd.DataFrame(columns=strikes, index=expiries)
for expiry, row in df.iterrows():
    for strike in row.index:
        count = 0
        for quote_time, group in groups:
            if expiry in group["[EXPIRE_DATE]"].values and strike in group["[STRIKE]"].values:
                count += 1
        pct = count / len(groups)
        df.loc[expiry, strike] = pct

df

,320.0,330.0,336.0,337.0,338.0,339.0,340.0,341.0,342.0,343.0,...,501.0,502.0,503.0,155.0,165.0,175.0,715.0,120.0,130.0,140.0
2023-03-01,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,...,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478
2023-03-02,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,...,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957
2023-03-03,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,...,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435
2023-03-06,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,...,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913
2023-03-07,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,...,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391
2023-03-08,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,...,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087
2023-03-09,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,...,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348
2023-03-10,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,...,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826
2023-03-13,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,...,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304
2023-03-14,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,...,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783
2023-03-15,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-17,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,...,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217
2023-03-24,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,...,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609
2023-03-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-04-06,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-04-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-05-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-06-16,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-06-30,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-07-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-08-18,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-09-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-09-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-12-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-12-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-01-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-03-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-06-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-12-20,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2025-01-17,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2025-03-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2025-12-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-03-16,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-04-14,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,...,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522
2023-10-20,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,...,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522
2023-03-20,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-21,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-22,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-23,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-04-28,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,...,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913
2023-03-27,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-28,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-29,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-30,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-04-03,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,...,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783
2023-04-04,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,...,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304
2023-04-05,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,...,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826
2023-05-05,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,...,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348
2023-04-10,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,...,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391
2023-04-11,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,...,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913
2023-04-12,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,...,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435
2023-04-13,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,...,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957
2023-05-12,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,...,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957

In [10]:
pairs = []
for expiry, row in df.iterrows():
    for strike in row.index:
        if df.loc[expiry, strike] == 1.0:
            pairs.append((expiry, strike))

expiries = np.array([x[0] for x in pairs])
strikes = np.array([x[1] for x in pairs])
np.save(Path.cwd().parent / "nn_learning" / "expiries_being_used.npy", expiries)
np.save(Path.cwd().parent / "nn_learning" / "strikes_being_used.npy", strikes)
print("expiries")
print(expiries)
print("strikes")
print(strikes)
print()
print('num of pairs that appear everywhere:', len(pairs))

print('num of pairs that dont appear everywhere:', len(df)*len(df.columns) - len(pairs))

expiries
[' 2023-03-31' ' 2023-03-31' ' 2023-03-31' ... ' 2025-12-19' ' 2025-12-19'
 ' 2025-12-19']
strikes
[320. 330. 336. ... 120. 130. 140.]

num of pairs that appear everywhere: 5472
num of pairs that dont appear everywhere: 9845

In [ ]:
# get earliest quote
print(type(quotes[0]))

<ArrowStringArray>
[' 2023-03-01 16:00', ' 2023-03-02 16:00', ' 2023-03-03 16:00',
 ' 2023-03-06 16:00', ' 2023-03-07 16:00', ' 2023-03-08 16:00',
 ' 2023-03-09 16:00', ' 2023-03-10 16:00', ' 2023-03-13 16:00',
 ' 2023-03-14 16:00', ' 2023-03-15 16:00', ' 2023-03-16 16:00',
 ' 2023-03-17 16:00', ' 2023-03-20 16:00', ' 2023-03-21 16:00',
 ' 2023-03-22 16:00', ' 2023-03-23 16:00', ' 2023-03-24 16:00',
 ' 2023-03-27 16:00', ' 2023-03-28 16:00', ' 2023-03-29 16:00',
 ' 2023-03-30 16:00', ' 2023-03-31 16:00']
Length: 23, dtype: str