In [13]:
import numpy as np
import pandas as pd
from pathlib import Path

df = pd.read_csv(Path.cwd().parent / "data" / "spy_eod_202303.txt")
df.columns = [k.strip(' ') for k in df.columns]
df

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.01,-0.00069,0.00008,-0.00004,-0.00482,0.00000,1.486360,0.000000,74.8,0.189
1,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.02,-0.00080,0.00011,0.00034,-0.00529,0.00000,1.282980,0.000000,64.8,0.164
2,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.00,-0.00075,0.00014,0.00100,-0.00509,-0.00046,1.162910,,58.8,0.149
3,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.00,-0.00128,0.00020,0.00096,-0.00470,0.00000,1.143500,,57.8,0.146
4,1677704400,2023-03-01 16:00,2023-03-01,16.0,394.76,2023-03-01,1677704400,0.00,1.00000,0.00000,...,0.00,-0.00050,0.00015,0.00027,-0.00523,-0.00017,1.123140,,56.8,0.144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91230,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.08235,0.00152,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,220.6,0.539
91231,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.08401,0.00146,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,225.6,0.551
91232,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.06465,0.00132,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,230.6,0.563
91233,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.07999,0.00138,...,0.00,-1.00000,0.00000,0.00000,0.00000,0.00000,,,235.6,0.576
91234,1680292800,2023-03-31 16:00,2023-03-31,16.0,409.39,2025-12-19,1766178000,994.04,0.05785,0.00116,...,240.32,-1.00000,0.00000,0.00000,0.00000,0.00000,,0.000000,240.6,0.588

In [ ]:

expiries_used = np.load(Path.cwd().parent / "nn_learning_intensity" / "expiries_being_used.npy", allow_pickle=True)
strikes_used = np.load(Path.cwd().parent / "nn_learning_intensity" / "strikes_being_used.npy", allow_pickle=True)

count_strikes = {}
count_expiries = {}

groups = df.groupby(["[QUOTE_READTIME]"])
for quote, group in groups:
    for strike in group["[STRIKE]"].values:
        if strike in count_strikes.keys():
            count_strikes[strike] += 1
        else:
            count_strikes[strike] = 0
    for expiry in group["[EXPIRE_DATE]"].values:
        if expiry in count_expiries.keys():
            count_expiries[expiry] += 1
        else:
            count_expiries[expiry] = 0

count_strikes = [(x,y) for x,y in zip(count_strikes.keys(), count_strikes.values())]
count_expiries = [(x,y) for x,y in zip(count_expiries.keys(), count_expiries.values())]
strikes_tb_used = sorted(count_strikes, key=lambda x: x[1])
expiries_tb_used = sorted(count_expiries, key=lambda x: x[1])
print(expiries_tb_used)
print(strikes_tb_used)

[(' 2023-04-13', 69), (' 2023-03-01', 140), (' 2023-04-12', 143), (' 2023-05-12', 157), (' 2023-03-02', 255), (' 2023-04-11', 396), (' 2023-03-03', 452), (' 2023-03-06', 507), (' 2023-04-10', 521), (' 2023-03-07', 634), (' 2023-05-05', 687), (' 2023-03-08', 731), (' 2023-03-09', 861), (' 2023-04-05', 905), (' 2023-04-04', 955), (' 2023-03-13', 1028), (' 2023-03-14', 1158), (' 2023-04-03', 1163), (' 2023-03-22', 1184), (' 2023-03-10', 1200), (' 2023-03-16', 1224), (' 2023-03-30', 1241), (' 2023-03-20', 1246), (' 2023-03-23', 1271), (' 2023-03-15', 1282), (' 2023-03-29', 1292), (' 2023-03-28', 1308), (' 2023-03-21', 1332), (' 2023-03-27', 1337), (' 2023-04-28', 1762), (' 2024-03-15', 1946), (' 2023-10-20', 2001), (' 2025-01-17', 2046), (' 2025-03-21', 2046), (' 2024-06-21', 2115), (' 2023-07-21', 2322), (' 2025-12-19', 2322), (' 2023-04-14', 2391), (' 2024-01-19', 2483), (' 2023-12-29', 2575), (' 2023-08-18', 2576), (' 2023-09-29', 2598), (' 2024-12-20', 2644), (' 2023-03-24', 2692), (' 2023-06-30', 2736), (' 2023-04-06', 2751), (' 2023-12-15', 3064), (' 2023-03-17', 3091), (' 2023-09-15', 3501), (' 2023-05-19', 3564), (' 2023-04-21', 3639), (' 2023-03-31', 4658), (' 2023-06-16', 4980)]
[(np.float64(417.5), 17), (np.float64(476.0), 22), (np.float64(477.0), 22), (np.float64(478.0), 22), (np.float64(479.0), 22), (np.float64(481.0), 22), (np.float64(482.0), 22), (np.float64(483.0), 22), (np.float64(484.0), 22), (np.float64(486.0), 22), (np.float64(487.0), 22), (np.float64(488.0), 22), (np.float64(489.0), 22), (np.float64(491.0), 22), (np.float64(492.0), 22), (np.float64(493.0), 22), (np.float64(494.0), 22), (np.float64(496.0), 22), (np.float64(497.0), 22), (np.float64(498.0), 22), (np.float64(499.0), 22), (np.float64(501.0), 22), (np.float64(502.0), 22), (np.float64(503.0), 22), (np.float64(120.0), 22), (np.float64(130.0), 22), (np.float64(140.0), 22), (np.float64(461.0), 23), (np.float64(462.0), 23), (np.float64(463.0), 23), (np.float64(464.0), 23), (np.float64(466.0), 23), (np.float64(467.0), 23), (np.float64(468.0), 23), (np.float64(469.0), 23), (np.float64(471.0), 23), (np.float64(472.0), 23), (np.float64(473.0), 23), (np.float64(474.0), 23), (np.float64(382.5), 24), (np.float64(301.0), 35), (np.float64(302.0), 35), (np.float64(303.0), 35), (np.float64(304.0), 35), (np.float64(306.0), 35), (np.float64(307.0), 35), (np.float64(308.0), 35), (np.float64(309.0), 35), (np.float64(311.0), 44), (np.float64(312.0), 44), (np.float64(313.0), 44), (np.float64(314.0), 44), (np.float64(715.0), 45), (np.float64(316.0), 52), (np.float64(317.0), 52), (np.float64(412.5), 57), (np.float64(318.0), 59), (np.float64(319.0), 59), (np.float64(387.5), 81), (np.float64(321.0), 86), (np.float64(322.0), 86), (np.float64(323.0), 86), (np.float64(324.0), 86), (np.float64(407.5), 96), (np.float64(392.5), 99), (np.float64(397.5), 99), (np.float64(402.5), 99), (np.float64(655.0), 104), (np.float64(660.0), 104), (np.float64(665.0), 104), (np.float64(670.0), 104), (np.float64(675.0), 104), (np.float64(680.0), 104), (np.float64(685.0), 104), (np.float64(690.0), 104), (np.float64(695.0), 104), (np.float64(700.0), 104), (np.float64(705.0), 104), (np.float64(710.0), 104), (np.float64(720.0), 104), (np.float64(459.0), 132), (np.float64(326.0), 132), (np.float64(327.0), 132), (np.float64(328.0), 132), (np.float64(155.0), 136), (np.float64(165.0), 136), (np.float64(175.0), 136), (np.float64(457.0), 138), (np.float64(458.0), 155), (np.float64(329.0), 169), (np.float64(331.0), 169), (np.float64(456.0), 171), (np.float64(640.0), 173), (np.float64(645.0), 173), (np.float64(650.0), 173), (np.float64(453.0), 179), (np.float64(332.0), 179), (np.float64(333.0), 179), (np.float64(334.0), 188), (np.float64(150.0), 195), (np.float64(160.0), 195), (np.float64(170.0), 195), (np.float64(451.0), 196), (np.float64(625.0), 196), (np.float64(630.0), 196), (np.float64(635.0), 196), (np.float64(449.0), 211), (np.float64(454.0), 216), (np.float64(452.0), 218), (np.float64(447.0), 233), (np.float64(433.0), 241), (np.float64(437.0), 241), (np.float64(439.0), 241), (np.float64(441.0), 241), (np.float64(443.0), 241), (np.float64(620.0), 242), (np.float64(431.0), 249), (np.float64(605.0), 265), (np.float64(610.0), 265), (np.float64(615.0), 265), (np.float64(336.0), 271), (np.float64(448.0), 287), (np.float64(446.0), 288), (np.float64(337.0), 294), (np.float64(338.0), 294), (np.float64(427.0), 295), (np.float64(429.0), 295), (np.float64(339.0), 297), (np.float64(180.0), 310), (np.float64(185.0), 310), (np.float64(190.0), 310), (np.float64(341.0), 318), (np.float64(342.0), 318), (np.float64(343.0), 318), (np.float64(344.0), 318), (np.float64(421.0), 319), (np.float64(423.0), 319), (np.float64(347.0), 322), (np.float64(349.0), 322), (np.float64(444.0), 325), (np.float64(595.0), 333), (np.float64(600.0), 333), (np.float64(346.0), 335), (np.float64(348.0), 335), (np.float64(442.0), 336), (np.float64(195.0), 340), (np.float64(351.0), 345), (np.float64(353.0), 345), (np.float64(357.0), 345), (np.float64(359.0), 345), (np.float64(438.0), 352), (np.float64(436.0), 355), (np.float64(200.0), 356), (np.float64(205.0), 356), (np.float64(210.0), 356), (np.float64(215.0), 356), (np.float64(220.0), 356), (np.float64(225.0), 356), (np.float64(230.0), 356), (np.float64(235.0), 356), (np.float64(240.0), 356), (np.float64(245.0), 356), (np.float64(565.0), 356), (np.float64(570.0), 356), (np.float64(575.0), 356), (np.float64(580.0), 356), (np.float64(585.0), 356), (np.float64(590.0), 356), (np.float64(434.0), 363), (np.float64(432.0), 365), (np.float64(550.0), 376), (np.float64(555.0), 376), (np.float64(560.0), 376), (np.float64(250.0), 380), (np.float64(361.0), 381), (np.float64(363.0), 381), (np.float64(367.0), 398), (np.float64(369.0), 398), (np.float64(535.0), 399), (np.float64(540.0), 399), (np.float64(545.0), 399), (np.float64(417.0), 404), (np.float64(419.0), 404), (np.float64(413.0), 409), (np.float64(428.0), 410), (np.float64(352.0), 412), (np.float64(354.0), 413), (np.float64(426.0), 413), (np.float64(424.0), 415), (np.float64(418.0), 416), (np.float64(422.0), 416), (np.float64(416.0), 417), (np.float64(414.0), 419), (np.float64(525.0), 422), (np.float64(530.0), 422), (np.float64(371.0), 427), (np.float64(356.0), 434), (np.float64(412.0), 434), (np.float64(358.0), 439), (np.float64(510.0), 444), (np.float64(362.0), 445), (np.float64(364.0), 445), (np.float64(373.0), 445), (np.float64(505.0), 445), (np.float64(515.0), 445), (np.float64(520.0), 445), (np.float64(411.0), 447), (np.float64(366.0), 449), (np.float64(368.0), 449), (np.float64(372.0), 450), (np.float64(374.0), 450), (np.float64(376.0), 456), (np.float64(379.0), 456), (np.float64(378.0), 457), (np.float64(409.0), 458), (np.float64(377.0), 464), (np.float64(407.0), 466), (np.float64(408.0), 468), (np.float64(404.0), 469), (np.float64(406.0), 469), (np.float64(399.0), 470), (np.float64(401.0), 470), (np.float64(403.0), 470), (np.float64(402.0), 471), (np.float64(255.0), 477), (np.float64(260.0), 477), (np.float64(265.0), 477), (np.float64(381.0), 484), (np.float64(382.0), 490), (np.float64(383.0), 491), (np.float64(384.0), 494), (np.float64(387.0), 497), (np.float64(270.0), 500), (np.float64(386.0), 502), (np.float64(388.0), 515), (np.float64(389.0), 515), (np.float64(397.0), 516), (np.float64(398.0), 517), (np.float64(391.0), 518), (np.float64(392.0), 518), (np.float64(393.0), 518), (np.float64(394.0), 518), (np.float64(396.0), 518), (np.float64(275.0), 545), (np.float64(280.0), 545), (np.float64(285.0), 545), (np.float64(290.0), 545), (np.float64(295.0), 545), (np.float64(475.0), 548), (np.float64(480.0), 548), (np.float64(485.0), 548), (np.float64(490.0), 548), (np.float64(495.0), 548), (np.float64(500.0), 548), (np.float64(465.0), 549), (np.float64(300.0), 549), (np.float64(305.0), 549), (np.float64(315.0), 557), (np.float64(470.0), 559), (np.float64(310.0), 570), (np.float64(325.0), 581), (np.float64(460.0), 589), (np.float64(335.0), 646), (np.float64(455.0), 653), (np.float64(320.0), 690), (np.float64(330.0), 697), (np.float64(445.0), 709), (np.float64(345.0), 710), (np.float64(340.0), 715), (np.float64(355.0), 716), (np.float64(365.0), 716), (np.float64(435.0), 717), (np.float64(425.0), 719), (np.float64(375.0), 722), (np.float64(415.0), 724), (np.float64(350.0), 729), (np.float64(450.0), 733), (np.float64(385.0), 734), (np.float64(360.0), 740), (np.float64(370.0), 740), (np.float64(420.0), 740), (np.float64(430.0), 740), (np.float64(440.0), 740), (np.float64(405.0), 741), (np.float64(380.0), 742), (np.float64(395.0), 742), (np.float64(390.0), 743), (np.float64(400.0), 743), (np.float64(410.0), 743)]

In [32]:
N = 5
expiries_tb_used = [x[0] for x in expiries_tb_used[:N]]
strikes_tb_used = [x[0] for x in strikes_tb_used[:N]]
print(expiries_tb_used)
print(strikes_tb_used)

[' 2023-04-13', ' 2023-03-01', ' 2023-04-12', ' 2023-05-12', ' 2023-03-02']
[np.float64(417.5), np.float64(476.0), np.float64(477.0), np.float64(478.0), np.float64(479.0)]

In [ ]:
    for quote, group in groups:
        print('quote:', quote)
        c = group[
            (group["[STRIKE]"].isin(strikes_tb_used))
            &
            (group["[EXPIRE_DATE]"].isin(expiries_tb_used))
            ]
        print(len(c))

quote: (' 2023-03-01 16:00',)
0
quote: (' 2023-03-02 16:00',)
0
quote: (' 2023-03-03 16:00',)
0
quote: (' 2023-03-06 16:00',)
0
quote: (' 2023-03-07 16:00',)
0
quote: (' 2023-03-08 16:00',)
0
quote: (' 2023-03-09 16:00',)
0
quote: (' 2023-03-10 16:00',)
0
quote: (' 2023-03-13 16:00',)
0
quote: (' 2023-03-14 16:00',)
0
quote: (' 2023-03-15 16:00',)
0
quote: (' 2023-03-16 16:00',)
0
quote: (' 2023-03-17 16:00',)
0
quote: (' 2023-03-20 16:00',)
0
quote: (' 2023-03-21 16:00',)
0
quote: (' 2023-03-22 16:00',)
0
quote: (' 2023-03-23 16:00',)
0
quote: (' 2023-03-24 16:00',)
0
quote: (' 2023-03-27 16:00',)
0
quote: (' 2023-03-28 16:00',)
0
quote: (' 2023-03-29 16:00',)
0
quote: (' 2023-03-30 16:00',)
0
quote: (' 2023-03-31 16:00',)
0

In [ ]:
selected = df[df["[STRIKE]"] == 130.0]
print(selected)

In [19]:
quotes = pd.to_datetime(df["[QUOTE_READTIME]"].unique())
print(quotes.min(), quotes.max())
strikes = df["[STRIKE]"].unique()
expiries = df["[EXPIRE_DATE]"].unique()

print('num of quotes:', len(quotes))
print('num strikes:', len(strikes))
print('num expiries:', len(expiries))

groups = df.groupby(["[QUOTE_READTIME]"])

for quote_time, group in groups:
    print(len(group["[STRIKE]"].unique()))
    print(len(group["[EXPIRE_DATE]"].unique()))
    print()

2023-03-01 16:00:00 2023-03-31 16:00:00
num of quotes: 23
num strikes: 289
num expiries: 53
289
32

289
34

289
33

289
33

289
33

289
33

289
34

289
33

289
33

289
33

289
33

289
33

289
32

289
32

289
32

289
32

289
32

289
31

288
31

288
31

288
31

288
32

288
31

In [4]:
df = pd.DataFrame(columns=strikes, index=expiries)
for expiry, row in df.iterrows():
    for strike in row.index:
        count = 0
        for quote_time, group in groups:
            if expiry in group["[EXPIRE_DATE]"].values and strike in group["[STRIKE]"].values:
                count += 1
        pct = count / len(groups)
        df.loc[expiry, strike] = pct

df

,320.0,330.0,336.0,337.0,338.0,339.0,340.0,341.0,342.0,343.0,...,501.0,502.0,503.0,155.0,165.0,175.0,715.0,120.0,130.0,140.0
2023-03-01,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,...,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478,0.043478
2023-03-02,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,...,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957
2023-03-03,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,...,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435
2023-03-06,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,...,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913
2023-03-07,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,...,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391
2023-03-08,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,...,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087,0.26087
2023-03-09,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,...,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348
2023-03-10,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,...,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826
2023-03-13,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,...,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304
2023-03-14,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,...,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783
2023-03-15,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-17,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,...,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217,0.565217
2023-03-24,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,...,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609,0.782609
2023-03-31,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-04-06,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-04-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-05-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-06-16,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-06-30,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-07-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-08-18,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-09-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-09-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-12-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-12-29,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-01-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-03-15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-06-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2024-12-20,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2025-01-17,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2025-03-21,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2025-12-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2023-03-16,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-04-14,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,...,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522
2023-10-20,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,...,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522,0.956522
2023-03-20,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-21,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-22,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-23,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-04-28,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,...,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913,0.73913
2023-03-27,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-28,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-29,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-03-30,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,...,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261,0.478261
2023-04-03,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,...,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783,0.434783
2023-04-04,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,...,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304,0.391304
2023-04-05,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,...,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826,0.347826
2023-05-05,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,...,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348,0.304348
2023-04-10,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,...,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391,0.217391
2023-04-11,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,...,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913,0.173913
2023-04-12,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,...,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435,0.130435
2023-04-13,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,...,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957
2023-05-12,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,...,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957,0.086957

In [10]:
pairs = []
for expiry, row in df.iterrows():
    for strike in row.index:
        if df.loc[expiry, strike] == 1.0:
            pairs.append((expiry, strike))

expiries = np.array([x[0] for x in pairs])
strikes = np.array([x[1] for x in pairs])
np.save(Path.cwd().parent / "nn_learning" / "expiries_being_used.npy", expiries)
np.save(Path.cwd().parent / "nn_learning" / "strikes_being_used.npy", strikes)
print("expiries")
print(expiries)
print("strikes")
print(strikes)
print()
print('num of pairs that appear everywhere:', len(pairs))

print('num of pairs that dont appear everywhere:', len(df)*len(df.columns) - len(pairs))

expiries
[' 2023-03-31' ' 2023-03-31' ' 2023-03-31' ... ' 2025-12-19' ' 2025-12-19'
 ' 2025-12-19']
strikes
[320. 330. 336. ... 120. 130. 140.]

num of pairs that appear everywhere: 5472
num of pairs that dont appear everywhere: 9845

In [15]:
# get earliest quote
quotes_fixed = [quote[1:] for quote in quotes]
quotes_fixed = pd.to_datetime(quotes_fixed)
print(quotes_fixed.min())
print(quotes_fixed.max())

2023-03-01 16:00:00
2023-03-31 16:00:00